/**
 * .env file writer (atomic, ESM port).
 *
 * v3: per-key pull/push needs parseEnvFileToMap to read the
 * current local value of a single key without round-tripping the
 * whole file through generate_env.
 */
import fs from 'node:fs';
import path from 'node:path';

function needsQuoting(value) {
  if (value === '') return true;
  if (/[\s#"'\\]/.test(value)) return true;
  if (/^\s/.test(value) || /\s$/.test(value)) return true;
  if (value.includes('\n') || value.includes('\r')) return true;
  return false;
}

function escape(value) {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n').replace(/\r/g, '\\r').replace(/\t/g, '\\t');
}

export function formatValue(value) {
  if (typeof value !== 'string') value = String(value);
  return needsQuoting(value) ? `"${escape(value)}"` : value;
}

/**
 * Read an .env.example, return the ordered list of keys.
 */
export function parseEnvExample(filePath) {
  if (!fs.existsSync(filePath)) return [];
  const content = fs.readFileSync(filePath, 'utf8');
  const keys = [];
  for (const raw of content.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq < 0) continue;
    const key = line.slice(0, eq).trim();
    if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(key) && !keys.includes(key)) keys.push(key);
  }
  return keys;
}

/**
 * Parse any .env-shaped file (.env, .env.example, .env.local) into
 * a `{key: value}` map. Values are de-quoted with backslash escapes
 * unrolled; lines without an `=` or with malformed keys are
 * skipped. Missing files return {}.
 *
 * Used by pull_secret/push_secret to read the current local value
 * of one key.
 */
export function parseEnvFileToMap(filePath) {
  const out = {};
  if (!fs.existsSync(filePath)) return out;
  const content = fs.readFileSync(filePath, 'utf8');
  for (const raw of content.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq < 0) continue;
    const key = line.slice(0, eq).trim();
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) continue;
    let value = line.slice(eq + 1);
    // Strip surrounding double quotes and unescape.
    if (value.length >= 2 && value.startsWith('"') && value.endsWith('"')) {
      value = value
        .slice(1, -1)
        .replace(/\\n/g, '\n')
        .replace(/\\r/g, '\r')
        .replace(/\\t/g, '\t')
        .replace(/\\"/g, '"')
        .replace(/\\\\/g, '\\');
    }
    out[key] = value;
  }
  return out;
}

export function renderEnv(orderedKeys, valueMap, opts = {}) {
  const lines = [];
  lines.push(`# Generated by envpact-mcp on ${new Date().toISOString()}`);
  lines.push('# DO NOT COMMIT — add .env to .gitignore');
  if (opts.project) lines.push(`# project: ${opts.project}`);
  lines.push('');
  for (const key of orderedKeys) {
    if (key in valueMap) lines.push(`${key}=${formatValue(valueMap[key])}`);
  }
  return lines.join('\n') + '\n';
}

/**
 * Write/replace a single key in an existing .env file (atomic).
 * Preserves the line order, comments, and blank lines. If the key
 * is not present, append it before the trailing newline.
 *
 * Used by pull_secret to update one key without disturbing the
 * rest of the file.
 */
export function upsertEnvKey(filePath, key, value) {
  const formatted = `${key}=${formatValue(value)}`;
  let content = '';
  try { content = fs.readFileSync(filePath, 'utf8'); } catch (_e) { /* new file */ }

  const lines = content.split(/\r?\n/);
  const keyRe = new RegExp(`^\\s*${key.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\$&')}\\s*=`);
  let replaced = false;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    if (keyRe.test(line)) {
      lines[i] = formatted;
      replaced = true;
      break;
    }
  }

  let next;
  if (replaced) {
    next = lines.join('\n');
  } else if (content === '') {
    // Brand-new file: emit the standard header.
    next =
      `# Generated by envpact-mcp on ${new Date().toISOString()}\n` +
      `# DO NOT COMMIT — add .env to .gitignore\n\n` +
      `${formatted}\n`;
  } else {
    // Append before trailing blank line(s).
    while (lines.length && lines[lines.length - 1] === '') lines.pop();
    lines.push(formatted);
    next = lines.join('\n') + '\n';
  }

  writeAtomic(filePath, next);
}

export function writeAtomic(filePath, content) {
  const dir = path.dirname(path.resolve(filePath));
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  const tmp = `${filePath}.tmp.${process.pid}.${Date.now()}`;
  fs.writeFileSync(tmp, content, { encoding: 'utf8', mode: 0o600 });
  fs.renameSync(tmp, filePath);
}

// Backwards-compatible name kept for generate-env.js callers.
export const writeEnvAtomic = writeAtomic;

export function ensureGitignoreCovers(cwd, pattern) {
  const file = path.join(cwd, '.gitignore');
  let existing = '';
  try { existing = fs.readFileSync(file, 'utf8'); } catch (_e) { /* none */ }
  if (existing.split(/\r?\n/).some(l => l.trim() === pattern)) return false;
  const next = (existing && !existing.endsWith('\n') ? existing + '\n' : existing) + pattern + '\n';
  fs.writeFileSync(file, next);
  return true;
}
