/**
 * .env file writer (atomic, ESM port).
 */
import fs from 'node:fs';
import path from 'node:path';

function needsQuoting(value) {
  if (value === '') return true;
  if (/[\s#"'\\]/.test(value)) return true;
  if (/^\s/.test(value) || /\s$/.test(value)) return true;
  if (value.includes('\n') || value.includes('\r')) return true;
  return false;
}

function escape(value) {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n').replace(/\r/g, '\\r').replace(/\t/g, '\\t');
}

export function formatValue(value) {
  if (typeof value !== 'string') value = String(value);
  return needsQuoting(value) ? `"${escape(value)}"` : value;
}

export function parseEnvExample(filePath) {
  if (!fs.existsSync(filePath)) return [];
  const content = fs.readFileSync(filePath, 'utf8');
  const keys = [];
  for (const raw of content.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq < 0) continue;
    const key = line.slice(0, eq).trim();
    if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(key) && !keys.includes(key)) keys.push(key);
  }
  return keys;
}

export function renderEnv(orderedKeys, valueMap, opts = {}) {
  const lines = [];
  lines.push(`# Generated by envpact-mcp on ${new Date().toISOString()}`);
  lines.push('# DO NOT COMMIT — add .env to .gitignore');
  if (opts.environment) lines.push(`# environment: ${opts.environment}`);
  if (opts.project) lines.push(`# project: ${opts.project}`);
  lines.push('');
  for (const key of orderedKeys) {
    if (key in valueMap) lines.push(`${key}=${formatValue(valueMap[key])}`);
  }
  return lines.join('\n') + '\n';
}

export function writeEnvAtomic(filePath, content) {
  const dir = path.dirname(path.resolve(filePath));
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  const tmp = `${filePath}.tmp.${process.pid}.${Date.now()}`;
  fs.writeFileSync(tmp, content, { encoding: 'utf8', mode: 0o600 });
  fs.renameSync(tmp, filePath);
}

export function ensureGitignoreCovers(cwd, pattern) {
  const file = path.join(cwd, '.gitignore');
  let existing = '';
  try { existing = fs.readFileSync(file, 'utf8'); } catch (_e) {}
  if (existing.split(/\r?\n/).some(l => l.trim() === pattern)) return false;
  const next = (existing && !existing.endsWith('\n') ? existing + '\n' : existing) + pattern + '\n';
  fs.writeFileSync(file, next);
  return true;
}
