/**
 * generate-global-env.test.js — covers the v3.1 generate_global_env
 * tool and the underlying lib/global-env.js helper.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';

// Sandbox HOME so we don't touch the live ~/.envpact.
const TEST_HOME = fs.mkdtempSync(path.join(os.tmpdir(), 'envpact-mcp-global-'));
process.env.USERPROFILE = TEST_HOME;
process.env.HOME = TEST_HOME;

const { CONFIG_DIR, SECRETS_DIR, SECRETS_FILE } = await import('../src/lib/config.js');
const { generateGlobalEnvHandler } = await import('../src/tools/generate-global-env.js');
const {
  ensureGlobalExample,
  generateGlobalEnv,
  renderGlobalBody,
  GLOBAL_ENV_FILE,
  GLOBAL_EXAMPLE_FILE,
} = await import('../src/lib/global-env.js');

assert.ok(
  CONFIG_DIR.startsWith(TEST_HOME),
  `Test isolation broken — CONFIG_DIR=${CONFIG_DIR} did not honour TEST_HOME=${TEST_HOME}`
);

const TS = '2026-06-19T10:00:00.000Z';

function entry(value) {
  return { value, _modified_at: TS };
}

function writeVault(vault) {
  fs.mkdirSync(SECRETS_DIR, { recursive: true });
  fs.writeFileSync(SECRETS_FILE, JSON.stringify(vault, null, 2));
}

test('ensureGlobalExample creates alphabetical example on first run', () => {
  // Wipe state from previous tests.
  try { fs.rmSync(GLOBAL_EXAMPLE_FILE); } catch (_e) { /* ok */ }
  const vault = {
    version: 3,
    shared: {
      ZEBRA: entry('z'),
      ALPHA: entry('a'),
      MIDDLE: entry('m'),
    },
    projects: {},
  };
  const created = ensureGlobalExample(vault);
  assert.equal(created, true);
  const text = fs.readFileSync(GLOBAL_EXAMPLE_FILE, 'utf8');
  assert.equal(text, 'ALPHA=\nMIDDLE=\nZEBRA=\n');

  // Idempotent on second call.
  const second = ensureGlobalExample(vault);
  assert.equal(second, false);
});

test('renderGlobalBody — KEY=VALUE, byte-faithful comments and blanks', () => {
  const example = [
    '# my-app top of file',
    '',
    'OPENAI_API_KEY=hint',
    '# section header',
    'STRIPE_SECRET_KEY=',
    'NOT_IN_VAULT=',
    '',
  ].join('\n') + '\n';

  const vault = {
    version: 3,
    shared: {
      OPENAI_API_KEY: entry('sk-real'),
      STRIPE_SECRET_KEY: entry('sk_live_with space'),
    },
    projects: {},
  };

  const r = renderGlobalBody(vault, example);
  assert.equal(r.resolved, 2);
  assert.deepEqual(r.encrypted, []);
  assert.deepEqual(r.notInVault, ['NOT_IN_VAULT']);
  // First three lines preserved.
  assert.match(r.body, /# my-app top of file\n\nOPENAI_API_KEY=sk-real\n/);
  // Whitespace value forces double-quoting.
  assert.match(r.body, /STRIPE_SECRET_KEY="sk_live_with space"\n/);
  // Missing key flagged inline.
  assert.match(r.body, /# NOT_IN_VAULT: not in vault/);
  // Header section preserved.
  assert.match(r.body, /# section header/);
});

test('renderGlobalBody — encrypted shared values become a comment, not a value', () => {
  const example = 'A=\nB=\n';
  const vault = {
    version: 3,
    shared: {
      A: entry('plain'),
      B: entry('enc:ciphertext'),
    },
    projects: {},
  };
  const r = renderGlobalBody(vault, example);
  assert.equal(r.resolved, 1);
  assert.deepEqual(r.encrypted, ['B']);
  assert.match(r.body, /A=plain/);
  assert.match(r.body, /# B: encrypted — decrypt-via-cli/);
  assert.doesNotMatch(r.body, /B=enc:/);
});

test('generateGlobalEnv writes ~/.envpact/.env and returns counts', () => {
  // Reset state.
  try { fs.rmSync(GLOBAL_EXAMPLE_FILE); } catch (_e) { /* ok */ }
  try { fs.rmSync(GLOBAL_ENV_FILE); } catch (_e) { /* ok */ }
  const vault = {
    version: 3,
    shared: {
      OPENAI_API_KEY: entry('sk-x'),
      ENC_KEY: entry('enc:bla'),
    },
    projects: {},
  };
  const r = generateGlobalEnv(vault);
  assert.equal(r.output_path, GLOBAL_ENV_FILE);
  assert.equal(r.generated_global_example, true);
  assert.equal(r.resolved_count, 1);
  assert.deepEqual(r.encrypted, ['ENC_KEY']);
  assert.deepEqual(r.not_in_vault, []);

  const out = fs.readFileSync(GLOBAL_ENV_FILE, 'utf8');
  assert.match(out, /^# Generated by envpact-mcp \(global\) on /m);
  assert.match(out, /OPENAI_API_KEY=sk-x/);
  assert.match(out, /# ENC_KEY: encrypted/);
});

test('generate_global_env tool — happy path returns structured payload', async () => {
  // Reset state.
  try { fs.rmSync(GLOBAL_EXAMPLE_FILE); } catch (_e) { /* ok */ }
  try { fs.rmSync(GLOBAL_ENV_FILE); } catch (_e) { /* ok */ }
  writeVault({
    version: 3,
    shared: {
      OPENAI_API_KEY: entry('sk-y'),
      DB_PASSWORD: entry('hunter2'),
    },
    projects: {},
  });

  const res = await generateGlobalEnvHandler({});
  assert.notEqual(res.isError, true);
  assert.equal(res.structuredContent.resolved_count, 2);
  assert.equal(res.structuredContent.generated_global_example, true);
  assert.equal(res.structuredContent.output_path, GLOBAL_ENV_FILE);
  assert.deepEqual(res.structuredContent.encrypted, []);
  assert.deepEqual(res.structuredContent.not_in_vault, []);
  // Body should NOT contain the actual secret value in the response
  // text (it's only on disk).
  assert.doesNotMatch(res.content[0].text, /sk-y/);
  assert.doesNotMatch(res.content[0].text, /hunter2/);

  // File on disk should have both values.
  const onDisk = fs.readFileSync(GLOBAL_ENV_FILE, 'utf8');
  assert.match(onDisk, /OPENAI_API_KEY=sk-y/);
  assert.match(onDisk, /DB_PASSWORD=hunter2/);
});

test('generate_global_env tool — output_path override', async () => {
  // Reset state so the example reflects only the current vault.
  try { fs.rmSync(GLOBAL_EXAMPLE_FILE); } catch (_e) { /* ok */ }
  writeVault({
    version: 3,
    shared: { K: entry('v') },
    projects: {},
  });
  const target = path.join(TEST_HOME, 'override.env');
  const res = await generateGlobalEnvHandler({ output_path: target });
  assert.notEqual(res.isError, true);
  assert.equal(res.structuredContent.output_path, target);
  assert.match(fs.readFileSync(target, 'utf8'), /K=v/);
});

test('generate_global_env tool — surfaces vault-load errors', async () => {
  // Trash the vault file so loadVault throws.
  fs.rmSync(SECRETS_FILE, { force: true });
  const res = await generateGlobalEnvHandler({});
  assert.equal(res.isError, true);
  assert.match(res.content[0].text, /not initialised|vault/i);
});
